#!/usr/bin/env bash
set -e

LF_ICONS=$(sed ~/.config/diricons \
              -e '/^[ \t]*#/d'       \
              -e '/^[ \t]*$/d'       \
              -e 's/[ \t]\+/=/g'     \
              -e 's/$/ /')
  LF_ICONS=${LF_ICONS//$'\n'/:}
  export LF_ICONS

cleanup() {
    exec 3>&-
	rm "$FIFO_UEBERZUG"
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	lf $@
else
	[ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
	export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
	mkfifo "$FIFO_UEBERZUG"
	ueberzug layer -s <"$FIFO_UEBERZUG" -p bash &
	exec 3>"$FIFO_UEBERZUG"
	trap cleanup EXIT
	lf "$@" 3>&-
fi
